(load-file  (concat (getenv "HOME") "/.emacs.d/key-bindings.el"))
(defun my-init()
  (shell-script-mode)
)
(defun my-exit()
  (interactive)
  (kill-emacs 2)
)
(global-set-key "\C-x\C-v" 'my-exit)
(add-hook 'after-init-hook #'my-init)
(add-hook 'after-init-hook #'linum-mode)
(setq-default major-mode 'shell-script-mode)
