#!/bin/bash
# Debian GNU/Linux cowbuilder(1) completion
# Copyright 2007 Cyril Brulebois <cyril.brulebois@enst-bretagne.fr>
# Copyright 2009 Junichi Uekawa
#
# This script can be distributed under the same license as the
# cowdancer or bash packages.

have qemubuilder &&
_qemubuilder()
{
    local initialcommand initialcommand_options cur prev other_options distribution

    COMPREPLY=()
    cur=$(_get_cword)
    prev=${COMP_WORDS[COMP_CWORD-1]}
    initialcommand=${COMP_WORDS[1]}
    initialcommand_options='--create --update --build --login --execute'
    other_options='--dumpconfig --distribution --mirror --basepath --architecture'
    distribution='sid sarge etch woody lenny squeeze'

    case $initialcommand in
        --build)
            COMPREPLY=( $( compgen -W "$other_options" | grep "^$cur" ) 
		$( compgen -o filenames -G "$cur*.dsc" ) )
            ;;
        --execute)
            COMPREPLY=( $( compgen -W "$other_options" | grep "^$cur" ) 
		$( compgen -o filenames -G "$cur*" ) )
            ;;
        *)
            COMPREPLY=( $( compgen -W "$initialcommand_options" | grep "^$cur" ) 
		$( compgen -W "$other_options" | grep "^$cur" ) 
		)
            ;;
    esac

    case $prev in
	--distribution)
	    COMPREPLY=( $(compgen -W "$distribution" | grep "^$cur"  ) )
	    ;;
	*)
    esac

    return 0
}
[ "$have" ] && complete -F _qemubuilder -o filenames qemubuilder
